name: Deploy to AWS

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

permissions:
  id-token: write
  contents: read

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" != "" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: determine-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # Compilar la aplicación Lambda primero (si el proyecto está en un directorio separado)
      - name: Build Lambda function
        working-directory: ../apikey-admin/apikey  # Ajusta esta ruta según la estructura de tu proyecto
        run: mvn clean package -DskipTests

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Mantener Node.js 16 para compatibilidad con CDK v1

      - name: Install specific CDK v1 version
        run: npm install -g aws-cdk@1.204.0  # Ajusta a la versión específica de CDK v1 que estás usando

      # Actualizar o crear el archivo cdk.json ajustado para CDK v1
      - name: Create CDK configuration
        run: |
          cat > cdk.json << EOF
          {
            "app": "mvn -e -q compile exec:java",
            "context": {
              "@aws-cdk/core:enableStackNameDuplicates": false,
              "aws-cdk:enableDiffNoFail": "true",
              "@aws-cdk/core:stackRelativeExports": "true",
              "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
              "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
              "@aws-cdk/aws-kms:defaultKeyPolicies": true,
              "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
              "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
              "CDK_DEFAULT_ACCOUNT": "${{ vars.AWS_ACCOUNT_ID }}",
              "CDK_DEFAULT_REGION": "${{ vars.AWS_REGION }}",
              "VPC_ID": "${{ vars.VPC_ID }}",
              "SUBNET_IDS": "${{ vars.SUBNET_IDS }}",
              "SECURITY_GROUP_IDS": "${{ vars.SECURITY_GROUP_IDS }}",
              "STAGE_NAME": "${{ vars.STAGE_NAME }}",
              "MONGODB_CONNECTION_STRING": "${{ secrets.MONGODB_CONNECTION_STRING }}"
            }
          }
          EOF

      - name: CDK Bootstrap (if needed)
        run: cdk bootstrap
        env:
          CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}

      # Agregar un sufijo al stack según el entorno
      - name: CDK Deploy
        run: |
          STACK_NAME="ApiKeyDeployStack-${{ needs.determine-environment.outputs.environment }}"
          
          # Si es producción, no usar sufijo para mantener compatibilidad con despliegues anteriores
          if [[ "${{ needs.determine-environment.outputs.environment }}" == "production" ]]; then
            STACK_NAME="ApiKeyDeployStack"
          fi
          
          cdk deploy $STACK_NAME --require-approval never
        env:
          CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          VPC_ID: ${{ vars.VPC_ID }}
          SUBNET_IDS: ${{ vars.SUBNET_IDS }}
          SECURITY_GROUP_IDS: ${{ vars.SECURITY_GROUP_IDS }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          LOG_CHAN: ${{ vars.LOG_CHAN }}
          ENVIRONMENT: ${{ needs.determine-environment.outputs.environment }}